name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/movie-api:latest
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/movie-api:latest
          docker stop movie-api || true
          docker rm movie-api || true
          docker run -d --name movie-api -p 5000:5000 \
            -v /mnt:/mnt \
            -v /mnt/external/seagate/movies:/mnt/external/movies \
            -v /mnt/movie-config:/mnt/movie-config \
            -e TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e FIREBASE_CREDENTIALS_PATH=${{ secrets.FIREBASE_CREDENTIALS_PATH }} \
            -e FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} \
            ${{ secrets.DOCKER_USERNAME }}/movie-api:latest
